# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flexe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66lexe.proto\x12\x05\x66lexe\"\x1d\n\x0eGenericRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\" \n\x0fGenericResponse\x12\r\n\x05reply\x18\x01 \x01(\x05\"j\n\tTTRequest\x12\x11\n\tidVehicle\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x61tasetPath\x18\x02 \x01(\t\x12\x11\n\tmodelName\x18\x03 \x01(\t\x12\x0e\n\x06\x65pochs\x18\x04 \x01(\x05\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\"/\n\rEvaluateReply\x12\x0c\n\x04loss\x18\x01 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x02 \x01(\x01\"0\n\nModelReply\x12\x11\n\tidVehicle\x18\x01 \x01(\x05\x12\x0f\n\x07tensors\x18\x02 \x03(\x0c\"d\n\x0cModelRequest\x12\x11\n\tidVehicle\x18\x01 \x01(\x05\x12\x0f\n\x07tensors\x18\x02 \x03(\x0c\x12\x1a\n\x12number_of_vehicles\x18\x03 \x01(\x05\x12\x14\n\x0cnum_examples\x18\x04 \x01(\x05\x32\xd7\x04\n\x05\x46lexe\x12,\n\x03\x66it\x12\x10.flexe.TTRequest\x1a\x11.flexe.ModelReply\"\x00\x12\x34\n\x08\x65valuate\x12\x10.flexe.TTRequest\x1a\x14.flexe.EvaluateReply\"\x00\x12:\n\x0cupdate_model\x12\x10.flexe.TTRequest\x1a\x16.flexe.GenericResponse\"\x00\x12>\n\x12\x61ggregate_evaluate\x12\x10.flexe.TTRequest\x1a\x14.flexe.EvaluateReply\"\x00\x12\x39\n\raggregate_fit\x12\x13.flexe.ModelRequest\x1a\x11.flexe.ModelReply\"\x00\x12@\n\x12\x61ggregate_sync_fit\x12\x15.flexe.GenericRequest\x1a\x11.flexe.ModelReply\"\x00\x12;\n\x0fserver_evaluate\x12\x10.flexe.TTRequest\x1a\x14.flexe.EvaluateReply\"\x00\x12<\n\x0bstore_model\x12\x13.flexe.ModelRequest\x1a\x16.flexe.GenericResponse\"\x00\x12>\n\x15initialize_parameters\x12\x10.flexe.TTRequest\x1a\x11.flexe.ModelReply\"\x00\x12\x36\n\x03\x65nd\x12\x15.flexe.GenericRequest\x1a\x16.flexe.GenericResponse\"\x00\x62\x06proto3')



_GENERICREQUEST = DESCRIPTOR.message_types_by_name['GenericRequest']
_GENERICRESPONSE = DESCRIPTOR.message_types_by_name['GenericResponse']
_TTREQUEST = DESCRIPTOR.message_types_by_name['TTRequest']
_EVALUATEREPLY = DESCRIPTOR.message_types_by_name['EvaluateReply']
_MODELREPLY = DESCRIPTOR.message_types_by_name['ModelReply']
_MODELREQUEST = DESCRIPTOR.message_types_by_name['ModelRequest']
GenericRequest = _reflection.GeneratedProtocolMessageType('GenericRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERICREQUEST,
  '__module__' : 'flexe_pb2'
  # @@protoc_insertion_point(class_scope:flexe.GenericRequest)
  })
_sym_db.RegisterMessage(GenericRequest)

GenericResponse = _reflection.GeneratedProtocolMessageType('GenericResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERICRESPONSE,
  '__module__' : 'flexe_pb2'
  # @@protoc_insertion_point(class_scope:flexe.GenericResponse)
  })
_sym_db.RegisterMessage(GenericResponse)

TTRequest = _reflection.GeneratedProtocolMessageType('TTRequest', (_message.Message,), {
  'DESCRIPTOR' : _TTREQUEST,
  '__module__' : 'flexe_pb2'
  # @@protoc_insertion_point(class_scope:flexe.TTRequest)
  })
_sym_db.RegisterMessage(TTRequest)

EvaluateReply = _reflection.GeneratedProtocolMessageType('EvaluateReply', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATEREPLY,
  '__module__' : 'flexe_pb2'
  # @@protoc_insertion_point(class_scope:flexe.EvaluateReply)
  })
_sym_db.RegisterMessage(EvaluateReply)

ModelReply = _reflection.GeneratedProtocolMessageType('ModelReply', (_message.Message,), {
  'DESCRIPTOR' : _MODELREPLY,
  '__module__' : 'flexe_pb2'
  # @@protoc_insertion_point(class_scope:flexe.ModelReply)
  })
_sym_db.RegisterMessage(ModelReply)

ModelRequest = _reflection.GeneratedProtocolMessageType('ModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELREQUEST,
  '__module__' : 'flexe_pb2'
  # @@protoc_insertion_point(class_scope:flexe.ModelRequest)
  })
_sym_db.RegisterMessage(ModelRequest)

_FLEXE = DESCRIPTOR.services_by_name['Flexe']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERICREQUEST._serialized_start=22
  _GENERICREQUEST._serialized_end=51
  _GENERICRESPONSE._serialized_start=53
  _GENERICRESPONSE._serialized_end=85
  _TTREQUEST._serialized_start=87
  _TTREQUEST._serialized_end=193
  _EVALUATEREPLY._serialized_start=195
  _EVALUATEREPLY._serialized_end=242
  _MODELREPLY._serialized_start=244
  _MODELREPLY._serialized_end=292
  _MODELREQUEST._serialized_start=294
  _MODELREQUEST._serialized_end=394
  _FLEXE._serialized_start=397
  _FLEXE._serialized_end=996
# @@protoc_insertion_point(module_scope)
